version: '3.2'

services:

  explorer-api:
    build: explorer-api/.
    image: polkascan/pre-explorer-api:latest
    hostname: explorer-api
    volumes:
      - './explorer-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Pasha111 # Change with configured password
      - DB_NAME=metascan
      - SUBSTRATE_RPC_URL=http://host.docker.internal:9933/
      - SUBSTRATE_ADDRESS_TYPE=42
      - TYPE_REGISTRY_FILE=app/type_registry/metablockchain_types.json
      - SUBSTRATE_METADATA_VERSION=12

  harvester-api:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - './harvester:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/
      - ENVIRONMENT=dev
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Pasha111 # Change with configured password
      - DB_NAME=metascan
      - SUBSTRATE_RPC_URL=http://host.docker.internal:9933/
      - TYPE_REGISTRY_FILE=app/type_registry/metablockchain_types.json
      - SUBSTRATE_ADDRESS_TYPE=42
      - SUBSTRATE_METADATA_VERSION=12
      - NEW_SESSION_EVENT_HANDLER=True
      - SUBSTRATE_STORAGE_BALANCE=Account
      - SUBSTRATE_STORAGE_INDICES=Accounts
      - FINALIZATION_ONLY=1
    depends_on:
      - redis

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    depends_on:
      - redis

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile=""
    environment: *env
    depends_on:
      - redis

  harvester-monitor:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    ports:
      - '5555:5555'
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: Metablockchain
        NETWORK_ID: dev
        NETWORK_TYPE: pre
        CHAIN_TYPE: relay
        NETWORK_TOKEN_SYMBOL: MUI
        NETWORK_TOKEN_DECIMALS: 6
        NETWORK_COLOR_CODE: 777777
        API_URL: http://127.0.0.1:8080/api/v1
    ports:
      - '8080:80'
    depends_on:
      - harvester-api
      - explorer-api

  polkadot-ui:
    image: polkasource/substrate-ui:polkadot-latest
    ports:
      - '8081:80'
